[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [12/Oct/2024 19:35:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2024 19:35:20] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:20] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:20] "[36mGET /static/images/i3.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:22] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [12/Oct/2024 19:35:22] "[32mGET /index HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [12/Oct/2024 19:35:22] "GET /login?next=/index HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2024 19:35:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:22] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:30] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [12/Oct/2024 19:35:30] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2024 19:35:30] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [12/Oct/2024 19:35:30] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [15/Oct/2024 17:17:25] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:17:26] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:17:26] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:17:26] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:17:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2024 17:21:58] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:21:58] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:21:59] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:21:59] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:22:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2024 17:26:53] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:26:53] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:26:54] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:26:54] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:26:54] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 17:27:00] "[32mPOST /login?next=/ HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:27:01] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:01] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:01] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:07] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:27:07] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:07] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:07] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 17:27:16] "[32mPOST /login HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:27:16] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:17] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 17:27:22] "[32mPOST /login?next=/ HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:27:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:22] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:22] "GET /static/images/i3.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:47] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:27:47] "[32mGET /index HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:27:47] "GET /login?next=/index HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:27:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:27:47] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [15/Oct/2024 17:28:10] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:28:10] "[35m[1mGET /login?next=/ HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                             ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
127.0.0.1 - - [15/Oct/2024 17:29:20] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:29:20] "[35m[1mGET /login?next=/ HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                             ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
127.0.0.1 - - [15/Oct/2024 17:30:29] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:30:29] "[35m[1mGET /login?next=/ HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                             ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
127.0.0.1 - - [15/Oct/2024 17:30:29] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2024 17:30:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:30:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:30:46] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:30:46] "GET /static/images/i3.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:30:49] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:30:49] "[32mGET /index HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:30:50] "[35m[1mGET /login?next=/index HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                             ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
127.0.0.1 - - [15/Oct/2024 17:30:59] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:30:59] "[35m[1mGET /login?next=/ HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                             ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
127.0.0.1 - - [15/Oct/2024 17:31:39] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:31:39] "[35m[1mGET /login?next=/ HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 67, in login
    return redirect(url_for('user', username=user.username))
                                         ^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'user' where it is not associated with a value
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [15/Oct/2024 17:32:10] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:32:10] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:32:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:32:11] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 17:32:18] "[32mPOST /login?next=/ HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:32:18] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:32:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:32:19] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:32:27] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:32:27] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:32:27] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:32:27] "GET /static/js/script.js HTTP/1.1" 200 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 17:32:40] "[32mPOST /login?next=/ HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:32:40] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:32:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:32:40] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:19] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:33:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:19] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:20] "GET /index HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:33:20] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:20] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:20] "GET /static/images/i3.png HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:33:35] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:33:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:33:35] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:34:23] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 17:34:23] "[32mGET /index HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:34:23] "GET /login?next=/index HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:34:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:34:24] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:34:26] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:34:26] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:34:26] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:38:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:38:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:38:51] "[36mGET /static/images/i3.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:38:51] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:39:06] "GET /user/myuser HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:39:06] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:39:06] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 17:39:20] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 17:39:20] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:39:20] "GET /static/css/style.css HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 17:39:20] "GET /static/js/script.js HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:05:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:05:33] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:33] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:33] "[36mGET /static/images/i3.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:39] "[32mGET /logout HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 18:05:39] "[32mGET /index HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 18:05:40] "GET /login?next=/index HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:05:41] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:42] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:45] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:05:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:05:46] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
127.0.0.1 - - [15/Oct/2024 18:06:16] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 18:06:16] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:06:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:06:17] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:06:19] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:06:20] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:06:20] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:10:26] "[32mGET / HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 18:10:26] "GET /login?next=/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:10:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:10:27] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:10:28] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:10:29] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:10:29] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:11:06] "[32mPOST /register HTTP/1.1[0m" 302 -
Проверка логгера
Пользователь не аутентифицирован
127.0.0.1 - - [15/Oct/2024 18:11:07] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [15/Oct/2024 18:11:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2024 18:11:08] "[36mGET /static/js/script.js HTTP/1.1[0m" 304 -
Проверка логгера
Пользователь не аутентифицирован
Ветвление validate_on_sumbit сработало
База данных открылась
127.0.0.1 - - [15/Oct/2024 18:11:18] "[32mPOST /login HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2024 18:11:18] "[35m[1mGET /user/android HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\werkzeug\serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\flask\myblog\app\routes.py", line 116, in user
    return render_template('user.html', user=user, posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\Programs\Python\flask\myblog\blogenv\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programs\Python\flask\myblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Programs\Python\flask\myblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Programs\Python\flask\myblog\app\templates\user.html", line 7, in block 'content'
    <img src="{{ user.avatar_url() }}" alt="{{ user.username }}'s avatar" width="150" height="150">
  File "D:\Programs\Python\flask\myblog\app\models.py", line 33, in avatar_url
    if self.avatar:
       ^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'avatar'
